# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: dipsy88/go-k8s
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  name: go-k8s
  type: NodePort
  externalPort: 30000
  internalPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


